language: cpp
dist: xenial
env: SPEC=linux-g++-64 CONFIG=debug
sudo: required

env:
  global:
    - CCACHE_CPP2=1
    - CCACHE_DISABLE=1
    - JOBS=4
    # - QT_FATAL_WARNINGS=1
    - SHADOW_BUILD_DIR=/tmp/shadow_build_dir

addons:
    apt:
        packages:
        - ccache
        - flite1-dev
        - libqt5svg5-dev
        - libsdl2-dev
        - libsdl1.2-dev
        - libsndfile-dev
        - libssl-dev
        - libudev-dev
        - qt5-make
        - qt5-default
        - qtdeclarative5-qtquick2-plugin

script:
    # run qmake
    - mkdir ${SHADOW_BUILD_DIR} && cd ${SHADOW_BUILD_DIR}
    - qmake -r ${TRAVIS_BUILD_DIR}/apm_planner.pro CONFIG+=${CONFIG} -spec ${SPEC}

    # compile
    - make -j$JOBS
    #- ccache -s

