#!/bin/sh
set -e

#ensure all users have permissions to access USB<->Adapters (dialout group)
awk -F: '$3 > 999 {print $1}' /etc/passwd | xargs -I USERNAME sudo adduser USERNAME dialout

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
