#!/bin/sh
echo "cccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccloolccccccccccccccccccc
cccccccccccccccccccccclollccldxdolcccccccccccccccc
ccccccccccccccccccccccodkkO0OkO00kdolccccccccccccc
ccccccccccccccccccccccccllox0XWWWWNX0kdlcccccccccc
cccccccccccccccccccccccccccccoxOKWMMMWNKkdlccccccc
ccccccccccclllllccccccclllllllllldkKNWMMMWX0xolccc
ccccccccccxKXXX0dcccccdKXXXXXXXX0kolokKNWMMMWXxccc
cccccccclkNMMMMNxccccl0WMMWX0KNMMW0lcclOWMMMNOlccc
cccccccoOWMNNWMWkccccxNMMMXdcoKMMWOlccdKMMWXxlcccc
ccccccdKWMXxOWMWOlccoKMMMMNOOKWMN0ocldKWMWKdcccccc
cccclxXWMWNKNWMM0lcckNMMNXXKKK0kdllld0WMNOoccccccc
ccclONMWXOOOKWMMKocoKMMWOolllccccldx0NMXklcccccccc
cccdO00OocccoO00kocdO00koccccccodxdONWKdcccccccccc
cccccccccccccccccccccccccccccldxdoxKN0occccccccccc
cccccccccccccccccccccccccccldddlco0Xklcccccccccccc
ccccccccccccccccccccccccloodolcclOKxcccccccccccccc
cccccccccccccccccccccccllllcccclxOoccccccccccccccc
cccccccccccccccccccccccccccccccodlcccccccccccccccc
cccccccccccccccccccccccccccccccllccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccc
"
if [ -f "release/apmplanner2.dmg" ] ; then
    rm -rf "release/apmplanner2.dmg"
fi

appdmg deploy/assets/config.json  release/apmplanner2.dmg
